# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class MproveCli < Formula
  desc "Mprove cli files"
  homepage "https://github.com/mprove-io/mprove-cli"
  url "https://github.com/mprove-io/mprove-cli/archive/refs/tags/12.0.6.tar.gz"
  version "12.0.6"
  sha256 "9e8d772a570d1d58008e9f69c6bb33733389c9981e7674c39ffe79cd7dc0cbb6"

  on_macos do
    on_intel do
      url "https://github.com/mprove-io/mprove-cli/releases/download/12.0.6/mprove-cli-12.0.6-darwin-amd64.tar.gz"
      sha256 "66c0240fb02e61e9e8598a26493a73c5b7812168cedfd808ae82f6f06f8e16cc"
    end

    on_arm do
      url "https://github.com/mprove-io/mprove-cli/releases/download/12.0.6/mprove-cli-12.0.6-darwin-arm64.tar.gz"
      sha256 "e74060d5828e4a5775401979f654f023d943fc3bf63da7350f3d0ea69f1771e2"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mprove-io/mprove-cli/releases/download/12.0.6/mprove-cli-12.0.6-linux-amd64.tar.gz"
      sha256 "c78e2a6e392ddd2dca17d23872059e546ef82dd1c12c23c70da24fa64ab70e0d"
    end
  end

  def install
    bin.install "mprove"
  end

  test do
    assert_match "mproveCLI", shell_output("#{bin}/mprove version")
  end
end
