# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class MproveCli < Formula
  desc "Mprove cli files"
  homepage "https://github.com/mprove-io/mprove-cli"
  url "https://github.com/mprove-io/mprove-cli/archive/refs/tags/11.0.101.tar.gz"
  version "11.0.101"
  sha256 "6e2a32137037d47a764ec42044c4e638e98d626b425983049d62c7a4b8cd100c"

  on_macos do
    on_intel do
      url "https://github.com/mprove-io/mprove-cli/releases/download/11.0.101/mprove-cli-11.0.101-darwin-amd64.tar.gz"
      sha256 "523693b6179dd440395b39682c673d3adb1737f4497200bf6e2e7c2818009b0d"
    end

    on_arm do
      url "https://github.com/mprove-io/mprove-cli/releases/download/11.0.101/mprove-cli-11.0.101-darwin-arm64.tar.gz"
      sha256 "75fe87b8f99ada58b7d18422b7cf6731dcbaad147f3266a5efa662c8526f301b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mprove-io/mprove-cli/releases/download/11.0.101/mprove-cli-11.0.101-linux-amd64.tar.gz"
      sha256 "14a19f39cbdbda1d7217344cbc4693e982c054ea238c4a1682cde5e424ea9934"
    end
  end

  def install
    bin.install "mprove"
  end

  test do
    assert_match "mproveCLI", shell_output("#{bin}/mprove version")
  end
end
